version: '3'
services:
  web:
    build: .
    ports:
      - '8080:8080'
    environment:
      NODE_ENV: production
      MONGO_HOST: mongo
      MONGO_PORT: 27017
    env_file:
      - .env
    depends_on:
      - mongo
  mongo:
    image: 'mongo:3.7'
    ports:
      - '27017:27017'
    volumes:
      - "mongo-data:/data/db"
      - "mongo-config:/data/configdb"
volumes:
  mongo-data:
  mongo-config:
